ANCHO = 600
ALTO = 700
SCREEN = (ANCHO, ALTO)
CENTRO = (ANCHO // 2, ALTO // 2)
MID_BOTTOM = (ANCHO // 2 , ALTO)
ORIGEN = (0,0)
ORIGEN_BASE = (0,540)

FPS = 120

NEGRO = (0, 0, 0)
BLANCO = (255,255,255)
CUSTOM = (121,121,222)
CUSTOM2 = (167,98,204)

FONT = 'Arial'

VIDA_POSICION = (480,630)

SIZE_VIDA = (120,40)
SIZE_ICONO = (32,32)
SIZE_VOLUMEN = (70,70)
SIZE_NAVE = (67,67)
SIZE_ASTEROIDE = (50,50)
SIZE_LASER = (10, 30)
SIZE_EXPLOSION = (70,70)
SIZE_POWER_UP = (35,35)

CENTER_X = ANCHO // 2

SPEED_NAVE = 5
SPEED_LASER = 10

SCORE_POS = (380,40)
TIEMPO_POS = (30,40)
NIVEL_POS = (30,80)
VOLUMEN_POS = (30, 555)

MAX_ASTEROIDES = 10
MAX_POWER_UPS = 1

DISPLAY_BOTTOM = ALTO
DISPLAY_TOP = 0
DISPLAY_LEFT = 0
DISPLAY_RIGHT = ANCHO
DISPLAY_CENTER_X = ANCHO // 2
DISPLAY_CENTER_Y = ALTO // 2
DISPLAY_MIDTOP = (DISPLAY_CENTER_X, DISPLAY_TOP)


INSTRUCCIONES ='''
 ~~~~~~~~~~~~~~~~~~~~~~~|Como Jugar|~~~~~~~~~~~~~~~~~~~~~~~~
  ↑: Para ir hacia arriba
  ↓: Para ir hacia abajo
  ←: Para ir hacía la izquierda
  →: Para ir hacia la derecha
  BARRA ESPACIADORA: Dispara laser
  OBJETIVO: ELIMINAR LA MAYOR CANTIDAD DE METEORITOS
            SIN SER GOLPEADO POR 3 DE ESTOS
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''